-- MySQL Script generated by MySQL Workbench
-- Wed Apr 22 17:18:20 2020
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema bottlecap
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `bottlecap` ;

-- -----------------------------------------------------
-- Schema bottlecap
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `bottlecap` DEFAULT CHARACTER SET utf8 ;
USE `bottlecap` ;

-- -----------------------------------------------------
-- Table `bottlecap`.`customer`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`customer` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`customer` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `is_organization` TINYINT NOT NULL,
  `name` VARCHAR(128) NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottlecap`.`order`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`order` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`order` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `quantity` VARCHAR(45) NOT NULL,
  `shipment_address` TEXT NOT NULL,
  `is_shipped` TINYINT NOT NULL,
  PRIMARY KEY (`id`, `customer_id`),
  INDEX `fk_order_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_order_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bottlecap`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottlecap`.`representative`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`representative` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`representative` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `phone_number` VARCHAR(16) NOT NULL,
  `password` VARCHAR(64) NOT NULL,
  `name` VARCHAR(128) NOT NULL,
  `email` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id`, `customer_id`),
  UNIQUE INDEX `phone_number_UNIQUE` (`phone_number` ASC) VISIBLE,
  UNIQUE INDEX `email_UNIQUE` (`email` ASC) VISIBLE,
  INDEX `fk_representative_customer_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_representative_customer`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bottlecap`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottlecap`.`payment`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`payment` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`payment` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `receipt` BLOB NOT NULL,
  `is_verified` TINYINT NOT NULL,
  `is_settlement` TINYINT NOT NULL,
  `amount` DECIMAL(22,2) NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `order_id`),
  UNIQUE INDEX `image_UNIQUE` (`receipt` ASC) VISIBLE,
  INDEX `fk_payment_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_payment_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `bottlecap`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottlecap`.`status`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`status` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`status` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `order_id` INT NOT NULL,
  `type` INT NOT NULL,
  `description` TEXT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `order_id`),
  INDEX `fk_status_order1_idx` (`order_id` ASC) VISIBLE,
  CONSTRAINT `fk_status_order1`
    FOREIGN KEY (`order_id`)
    REFERENCES `bottlecap`.`order` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottlecap`.`history`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`history` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`history` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `customer_id` INT NOT NULL,
  `activity` TEXT NOT NULL,
  `timestamp` DATETIME NOT NULL,
  PRIMARY KEY (`id`, `customer_id`),
  INDEX `fk_history_customer1_idx` (`customer_id` ASC) VISIBLE,
  CONSTRAINT `fk_history_customer1`
    FOREIGN KEY (`customer_id`)
    REFERENCES `bottlecap`.`customer` (`id`)
    ON DELETE CASCADE
    ON UPDATE CASCADE)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottlecap`.`client`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`client` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`client` (
  `id` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(64) NOT NULL,
  `secret` VARCHAR(128) NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `bottlecap`.`timestamps`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`timestamps` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`timestamps` (
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP,
  `update_time` TIMESTAMP NULL);


-- -----------------------------------------------------
-- Table `bottlecap`.`user`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`user` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`user` (
  `username` VARCHAR(16) NOT NULL,
  `email` VARCHAR(255) NULL,
  `password` VARCHAR(32) NOT NULL,
  `create_time` TIMESTAMP NULL DEFAULT CURRENT_TIMESTAMP);


-- -----------------------------------------------------
-- Table `bottlecap`.`category`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `bottlecap`.`category` ;

CREATE TABLE IF NOT EXISTS `bottlecap`.`category` (
  `category_id` INT NOT NULL,
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`category_id`));


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
